version : "3"
services:
  database:
    image: postgres:13
    restart: unless-stopped
    container_name: postgres-database
    ports:
      - 5432:5432
    env_file:
      - database.env
    volumes:
      - ./.database-data:/var/lib/postgresql/data/
  # client:
  #   build:
  #     context: ./client
  #     dockerfile: Dockerfile
  #   restart: unless-stopped
  #   container_name: client
  #   ports:
  #     - 3000:3001
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: server
    ports:
      - 5000:5000
    network_mode: "host"
    # network_mode: service:database
    depends_on:
      - database

# networks:
#   default:
#     driver: bridge

